import { resultChannel } from '../core/globals';
import { generate_dropdown_list, generate_bg_overlay, generate_overlay_dom, create_atcbl, generate_modal_host } from './generate';
import { setActiveButton } from '../core/store';
import { position_list, position_shadow_button_listener, manage_body_scroll, set_sizes } from './positioning';
import { log_event } from '../core/events';
import type { ATCBConfig } from '../types';

// FUNCTIONS TO CONTROL THE INTERACTION
function toggle(host: ShadowRoot, action: string, data: ATCBConfig | string = '', button: HTMLElement | string | null = null, keyboardTrigger: boolean = false, generatedButton: boolean = false): void {
  // programmatic flows expecting a computed value cannot show ui - suppress the list
  if (resultChannel.active()) {
    return;
  }
  // check for state and adjust accordingly
  // action can be 'open', 'close', or 'auto'
  if (action == 'open') {
    open(host, data as ATCBConfig, button, keyboardTrigger, generatedButton);
  } else if (action == 'close' || (button as HTMLElement).classList.contains('atcb-active') || host.querySelector('.atcb-active-modal')) {
    close(host, keyboardTrigger);
  } else {
    open(host, data as ATCBConfig, button, keyboardTrigger, generatedButton);
  }
}

// show the dropdown list + background overlay
async function open(host: ShadowRoot, data: ATCBConfig, button: HTMLElement | string | null = null, keyboardTrigger: boolean = false, generatedButton: boolean = false): Promise<void> {
  // abort early if an add to calendar dropdown or modal already opened
  if (host.querySelector('.atcb-list') || host.querySelector('.atcb-modal')) return;
  // log event
  log_event('openList', data.identifier!, data.identifier!);
  // generate list and prepare wrapper
  setActiveButton(data.identifier!);
  const list = generate_dropdown_list(host, data);
  const listWrapper = document.createElement('div');
  listWrapper.classList.add('atcb-list-wrapper');
  listWrapper.setAttribute('part', 'atcb-list-wrapper');
  if (data.hideTextLabelList) {
    listWrapper.classList.add('atcb-no-text');
  }
  // set list styles, set button to atcb-active and force modal as listStyle if no button is set
  if (button) {
    (button as HTMLElement).classList.add('atcb-active');
    (button as HTMLElement).setAttribute('aria-expanded', 'true');
    if (data.listStyle === 'modal') {
      (button as HTMLElement).classList.add('atcb-modal-style');
      list.classList.add('atcb-modal');
    } else {
      listWrapper.append(list);
      listWrapper.classList.add('atcb-dropdown');
      if (data.listStyle === 'overlay') {
        listWrapper.classList.add('atcb-dropoverlay');
      }
    }
    if (generatedButton) {
      list.classList.add('atcb-generated-button'); // if the button has been generated by the script, we add some more specifics
    }
  } else {
    list.classList.add('atcb-modal');
  }
  // render the items depending on the liststyle
  const bgOverlay = generate_bg_overlay(host, data.trigger, data.listStyle === 'modal', !data.hideBackground);
  if (data.listStyle === 'modal') {
    // define background overlay in its own new modal shadowDOM
    const modalHost: ShadowRoot = (await generate_modal_host(host, data))!;
    // append background overlay and list to the modal shadowDOM; and init helper functions
    modalHost.querySelector('.atcb-modal-host-initialized')!.append(bgOverlay);
    bgOverlay.append(list);
    if (!data.hideBranding) {
      create_atcbl(modalHost, false);
    }
    set_sizes(list, data.sizes!);
    manage_body_scroll(modalHost);
  } else {
    if (data.forceOverlay) {
      host = (await generate_overlay_dom(host, data)) as unknown as ShadowRoot;
      button = host.querySelector<HTMLElement>('button.atcb-button');
    }
    host.querySelector('.atcb-initialized')!.append(listWrapper);
    listWrapper.append(list);
    if (data.buttonStyle != 'default') {
      listWrapper.classList.add('atcb-style-' + data.buttonStyle);
    }
    if (!data.hideBranding) {
      create_atcbl(host);
    }
    // add background overlay to the main shadowDOM
    host.append(bgOverlay);
    set_sizes(list, data.sizes!);
    // setting the position with a tiny timeout to prevent any edge case situations, where the order gets mixed up
    listWrapper.style.display = 'none';
    setTimeout(function () {
      listWrapper.style.display = 'block';
      if (data.listStyle === 'dropdown-static') {
        // in the dropdown-static case, we do not dynamically adjust whether we show the dropdown upwards
        position_list(host, button as HTMLElement, listWrapper, true);
      } else if (data.listStyle === 'dropup-static') {
        // in the dropup-static case, we also do not dynamically adjust, but always show on top
        position_list(host, button as HTMLElement, listWrapper, false, true);
      } else {
        position_list(host, button as HTMLElement, listWrapper);
      }
    }, 5);
  }
  // give keyboard focus to first item in list, if possible
  const focusEl: HTMLElement | undefined = (function () {
    const hostEl = host.querySelector('[role="menuitem"]');
    if (hostEl) {
      return hostEl as HTMLElement;
    }
    const modalHost = document.getElementById(data.identifier + '-modal-host');
    if (!modalHost) {
      return;
    }
    return modalHost.shadowRoot!.querySelector('[role="menuitem"]') as HTMLElement;
  })();
  if (focusEl) {
    if (keyboardTrigger) {
      focusEl.focus();
    } else {
      focusEl.focus({ preventScroll: true });
      focusEl.blur();
    }
  }
}

function close(host: ShadowRoot, keyboardTrigger: boolean = false): void {
  // if we have a modal on a modal, close the latest first
  const existingModalHost = document.getElementById(host.host.getAttribute('atcb-button-id') + '-modal-host');
  const allModals: NodeListOf<Element> = (function () {
    if (!existingModalHost || (existingModalHost as unknown as { length?: number }).length === 0) {
      return [] as unknown as NodeListOf<Element>;
    }
    return existingModalHost.shadowRoot!.querySelectorAll('.atcb-modal[data-modal-nr]');
  })();
  if (allModals.length > 1) {
    existingModalHost!.shadowRoot!.querySelectorAll('.atcb-modal[data-modal-nr="' + allModals.length + '"]')[0]!.remove();
    const nextModal = existingModalHost!.shadowRoot!.querySelectorAll('.atcb-modal[data-modal-nr="' + (allModals.length - 1) + '"]')[0]!;
    nextModal.classList.remove('atcb-hidden');
    let focusEl: Element = nextModal;
    const availableButtons = nextModal.getElementsByTagName('button');
    if (availableButtons.length > 0) {
      focusEl = availableButtons[0]!;
    }
    (focusEl as HTMLElement).focus();
    if (!keyboardTrigger) {
      (focusEl as HTMLElement).blur();
    }
  } else {
    // focus triggering button if available - especially relevant for keyboard navigation
    const newFocusEl: Element | null = (function () {
      // find at host
      const hostEl = host.querySelector('.atcb-active, .atcb-active-modal');
      if (hostEl) {
        return hostEl;
      }
      // fallback to document (atcb_action case)
      return document.querySelector('.atcb-active, .atcb-active-modal');
    })();
    if (newFocusEl) {
      (newFocusEl as HTMLElement).focus({ preventScroll: true });
      if (!keyboardTrigger) {
        (newFocusEl as HTMLElement).blur();
      }
    }
    // inactivate all buttons at the host...
    Array.from(host.querySelectorAll('.atcb-active')).forEach((button: Element) => {
      button.classList.remove('atcb-active');
      button.setAttribute('aria-expanded', 'false');
    });
    Array.from(host.querySelectorAll('.atcb-active-modal')).forEach((modal: Element) => {
      modal.classList.remove('atcb-active-modal');
    });
    // ... as well as the document (case with atcb_action)
    Array.from(document.querySelectorAll('.atcb-active')).forEach((button: Element) => {
      button.classList.remove('atcb-active');
      button.setAttribute('aria-expanded', 'false');
    });
    Array.from(document.querySelectorAll('.atcb-active-modal')).forEach((modal: Element) => {
      modal.classList.remove('atcb-active-modal');
    });
    // remove any modal host
    if (existingModalHost) {
      existingModalHost.remove();
    }
    // make body scrollable again
    document.body.classList.remove('atcb-modal-no-scroll');
    document.documentElement.classList.remove('atcb-modal-no-scroll');
    // remove dropdowns, modals, and bg overlays (should only be one of each at max)
    Array.from(host.querySelectorAll('.atcb-list-wrapper'))
      .concat(Array.from(host.querySelectorAll('.atcb-list')))
      .concat(Array.from(host.querySelectorAll('#atcb-reference')))
      .concat(Array.from(host.querySelectorAll('#atcb-bgoverlay')))
      .forEach((el: Element) => el.remove());
    // show original button again (forceOverlay case)
    const hiddenButton = document.querySelector('.atcb-shadow-hide');
    if (hiddenButton) {
      (hiddenButton.shadowRoot!.querySelector('.atcb-initialized') as HTMLElement).style.opacity = '1';
      hiddenButton.classList.remove('atcb-shadow-hide');
      // also remove the event listener
      window.removeEventListener('scroll', position_shadow_button_listener);
      window.removeEventListener('resize', position_shadow_button_listener);
    }
    // reset active state
    setActiveButton('');
  }
}

export { toggle, open, close };
