export enum LanguageCode {
  AR = 'ar',
  BG = 'bg',
  CS = 'cs',
  DA = 'da',
  DE = 'de',
  EL = 'el',
  EN = 'en',
  ES = 'es',
  ET = 'et',
  FA = 'fa',
  FI = 'fi',
  FR = 'fr',
  HI = 'hi',
  HR = 'hr',
  HU = 'hu',
  ID = 'id',
  IT = 'it',
  JA = 'ja',
  KO = 'ko',
  LT = 'lt',
  MT = 'mt',
  NL = 'nl',
  NO = 'no',
  RO = 'ro',
  RU = 'ru',
  PL = 'pl',
  PT = 'pt',
  SV = 'sv',
  SK = 'sk',
  SL = 'sl',
  SR = 'sr',
  TR = 'tr',
  VI = 'vi',
  ZH = 'zh',
}

export const DefaultLanguageCode = LanguageCode.EN;

export const LanguageNames = {
  [LanguageCode.AR]: 'Arabic',
  [LanguageCode.BG]: 'Bulgarian',
  [LanguageCode.CS]: 'Czech',
  [LanguageCode.DA]: 'Danish',
  [LanguageCode.DE]: 'German',
  [LanguageCode.EL]: 'Greek',
  [LanguageCode.EN]: 'English',
  [LanguageCode.ES]: 'Spanish',
  [LanguageCode.ET]: 'Estonian',
  [LanguageCode.FA]: 'Persian',
  [LanguageCode.FI]: 'Finnish',
  [LanguageCode.FR]: 'French',
  [LanguageCode.HI]: 'Hindi',
  [LanguageCode.HR]: 'Hrvatski',
  [LanguageCode.HU]: 'Hungarian',
  [LanguageCode.ID]: 'Indonesian',
  [LanguageCode.IT]: 'Italian',
  [LanguageCode.JA]: 'Japanese',
  [LanguageCode.KO]: 'Korean',
  [LanguageCode.LT]: 'Lithuanian',
  [LanguageCode.MT]: 'Maltese',
  [LanguageCode.NL]: 'Dutch',
  [LanguageCode.NO]: 'Norwegian',
  [LanguageCode.RO]: 'Romanian',
  [LanguageCode.PL]: 'Polish',
  [LanguageCode.PT]: 'Portugese',
  [LanguageCode.RU]: 'Russian',
  [LanguageCode.SK]: 'Slovak',
  [LanguageCode.SL]: 'Slovenian',
  [LanguageCode.SR]: 'Serbian',
  [LanguageCode.SV]: 'Swedish',
  [LanguageCode.TR]: 'Turkish',
  [LanguageCode.VI]: 'Vietnamnese',
  [LanguageCode.ZH]: 'Chinese',
};
