export enum LanguageCode {
  AR = 'ar',
  AZ = 'az',
  BE = 'be',
  BG = 'bg',
  BS = 'bs',
  CS = 'cs',
  DA = 'da',
  DE = 'de',
  EL = 'el',
  EN = 'en',
  ES = 'es',
  ET = 'et',
  FA = 'fa',
  FI = 'fi',
  FR = 'fr',
  HE = 'he',
  HI = 'hi',
  HR = 'hr',
  HU = 'hu',
  HY = 'hy',
  ID = 'id',
  IT = 'it',
  JA = 'ja',
  KA = 'ka',
  KO = 'ko',
  LT = 'lt',
  LV = 'lv',
  MK = 'mk',
  MT = 'mt',
  NL = 'nl',
  NO = 'no',
  RO = 'ro',
  PL = 'pl',
  PT = 'pt',
  RU = 'ru',
  SK = 'sk',
  SL = 'sl',
  SQ = 'sq',
  SR = 'sr',
  SV = 'sv',
  TR = 'tr',
  UK = 'uk',
  VI = 'vi',
  ZH = 'zh',
}

export const DefaultLanguageCode = LanguageCode.EN;

export const LanguageNames = {
  [LanguageCode.AR]: 'Arabic',
  [LanguageCode.AZ]: 'Azerbaijani',
  [LanguageCode.BE]: 'Belarusian',
  [LanguageCode.BG]: 'Bulgarian',
  [LanguageCode.BS]: 'Bosnian',
  [LanguageCode.CS]: 'Czech',
  [LanguageCode.DA]: 'Danish',
  [LanguageCode.DE]: 'German',
  [LanguageCode.EL]: 'Greek',
  [LanguageCode.EN]: 'English',
  [LanguageCode.ES]: 'Spanish',
  [LanguageCode.ET]: 'Estonian',
  [LanguageCode.FA]: 'Persian',
  [LanguageCode.FI]: 'Finnish',
  [LanguageCode.FR]: 'French',
  [LanguageCode.HE]: 'Hebrew',
  [LanguageCode.HI]: 'Hindi',
  [LanguageCode.HR]: 'Croatian',
  [LanguageCode.HU]: 'Hungarian',
  [LanguageCode.HY]: 'Armenian',
  [LanguageCode.ID]: 'Indonesian',
  [LanguageCode.IT]: 'Italian',
  [LanguageCode.JA]: 'Japanese',
  [LanguageCode.KA]: 'Georgian',
  [LanguageCode.KO]: 'Korean',
  [LanguageCode.LT]: 'Lithuanian',
  [LanguageCode.LV]: 'Latvian',
  [LanguageCode.MK]: 'Macedonian',
  [LanguageCode.MT]: 'Maltese',
  [LanguageCode.NL]: 'Dutch',
  [LanguageCode.NO]: 'Norwegian',
  [LanguageCode.RO]: 'Romanian',
  [LanguageCode.PL]: 'Polish',
  [LanguageCode.PT]: 'Portuguese',
  [LanguageCode.RU]: 'Russian',
  [LanguageCode.SK]: 'Slovak',
  [LanguageCode.SL]: 'Slovenian',
  [LanguageCode.SQ]: 'Albanian',
  [LanguageCode.SR]: 'Serbian',
  [LanguageCode.SV]: 'Swedish',
  [LanguageCode.TR]: 'Turkish',
  [LanguageCode.UK]: 'Ukrainian',
  [LanguageCode.VI]: 'Vietnamese',
  [LanguageCode.ZH]: 'Chinese',
};
