export enum LanguageCode {
  EN = 'en',
  DE = 'de',
  NL = 'nl',
  FR = 'fr',
  ES = 'es',
  PT = 'pt',
  TR = 'tr',
  ZH = 'zh',
  HI = 'hi',
  PL = 'pl',
  ID = 'id',
  NO = 'no',
  FI = 'fi',
  SV = 'sv',
  CS = 'cs',
  JA = 'ja',
  IT = 'it',
  KO = 'ko',
  VI = 'vi',
  AR = 'ar',
}

export const DefaultLanguageCode = LanguageCode.EN;

export const LanguageNames = {
  [LanguageCode.EN]: 'English',
  [LanguageCode.DE]: 'German',
  [LanguageCode.NL]: 'Dutch',
  [LanguageCode.FR]: 'French',
  [LanguageCode.ES]: 'Spanish',
  [LanguageCode.PT]: 'Portugese',
  [LanguageCode.TR]: 'Turkish',
  [LanguageCode.ZH]: 'Chinese',
  [LanguageCode.HI]: 'Hindi',
  [LanguageCode.PL]: 'Polish',
  [LanguageCode.ID]: 'Indonesian',
  [LanguageCode.NO]: 'Norwegian',
  [LanguageCode.FI]: 'Finnish',
  [LanguageCode.SV]: 'Swedish',
  [LanguageCode.CS]: 'Czech',
  [LanguageCode.JA]: 'Japanese',
  [LanguageCode.IT]: 'Italian',
  [LanguageCode.KO]: 'Korean',
  [LanguageCode.VI]: 'Vietnamnese',
  [LanguageCode.AR]: 'Arabic',
};
